In [3]:
import zstandard as zstd

file_path = "3Dprinting_submissions.zst"

with open(file_path, 'rb') as f:
    dctx = zstd.ZstdDecompressor()
    with dctx.stream_reader(f) as reader:
        sample = reader.read(1024).decode('utf-8', errors ='ignore')
        print("\n".join(sample.splitlines()[:5]))

{"downs":0,"link_flair_text":null,"distinguished":null,"media":null,"url":"http://i.materialise.com/blog/entry/i-materialise-launches-dmls-you-can-now-3d-print-in-titanium","link_flair_css_class":null,"id":"f601l","edited":false,"num_reports":null,"created_utc":1295553456,"banned_by":null,"name":"t3_f601l","subreddit":"3Dprinting","title":"Upvote if you would like i.materialise to 3D print the reddit alien in titanium.","author_flair_text":null,"is_self":false,"author":"[deleted]","media_embed":{},"permalink":"/r/3Dprinting/comments/f601l/upvote_if_you_would_like_imaterialise_to_3d_print/","author_flair_css_class":null,"selftext":"","domain":"i.materialise.com","num_comments":0,"likes":null,"clicked":false,"thumbnail":"default","saved":false,"subreddit_id":"t5_2rk5q","ups":2,"approved_by":null,"score":2,"selftext_html":null,"created":1295553456,"hidden":false,"over_18":false}
{"downs":0,"link_flair_text":null,"distinguished":null,"media":null,"url":"http://www.3dfuture.com.au/2011/05/is-it-legal-to-print-sett

In [4]:
import pandas as pd

# Load only the first 5 rows
df_sample = pd.read_csv("3Dprinting_submissions.zst", nrows=5)
display(df_sample)

,"{""downs"":0",link_flair_text:null,distinguished:null,media:null,"url:""http://i.materialise.com/blog/entry/i-materialise-launches-dmls-you-can-now-3d-print-in-titanium""",link_flair_css_class:null,"id:""f601l""",edited:false,num_reports:null,created_utc:1295553456,...,"thumbnail:""default""",saved:false,"subreddit_id:""t5_2rk5q""",ups:2,approved_by:null,score:2,selftext_html:null,created:1295553456,hidden:false,over_18:false}
0,"{""downs"":0",link_flair_text:null,distinguished:null,media:null,"url:""http://www.3dfuture.com.au/2011/05/is-it-...",link_flair_css_class:null,"id:""hhkos""",edited:false,num_reports:null,created_utc:1306103426,...,"thumbnail:""default""",saved:false,"subreddit_id:""t5_2rk5q""",ups:1,approved_by:null,score:1,selftext_html:null,created:1306107026,hidden:false,over_18:false}
1,"{""downs"":0",link_flair_text:null,distinguished:null,media:null,"url:""http://www.boingboing.net/2011/06/25/sola...",link_flair_css_class:null,"id:""i913u""",edited:false,num_reports:null,created_utc:1309025337,...,"thumbnail:""default""",saved:false,"subreddit_id:""t5_2rk5q""",ups:1,approved_by:null,score:1,selftext_html:null,created:1309028937,hidden:false,over_18:false}
2,"{""downs"":0",link_flair_text:null,distinguished:null,media:null,"url:""http://www.3dfuture.com.au/2011/07/time-s...",link_flair_css_class:null,"id:""idnuz""",edited:false,num_reports:null,created_utc:1309471824,...,"thumbnail:""default""",saved:false,"subreddit_id:""t5_2rk5q""",ups:1,approved_by:null,score:1,selftext_html:null,created:1309475424,hidden:false,over_18:false}
3,"{""downs"":0",link_flair_text:null,distinguished:null,media:null,"url:""http://blog.ponoko.com/2011/07/07/3d-prin...",link_flair_css_class:null,"id:""imii7""",edited:false,num_reports:null,created_utc:1310401235,...,"thumbnail:""default""",saved:false,"subreddit_id:""t5_2rk5q""",ups:2,approved_by:null,score:2,selftext_html:null,created:1310404835,hidden:false,over_18:false}
4,"{""downs"":1",link_flair_text:null,distinguished:null,media:null,"url:""http://blog.ponoko.com/2011/07/13/z-corp-...",link_flair_css_class:null,"id:""ioinz""",edited:false,num_reports:null,created_utc:1310571920,...,"thumbnail:""default""",saved:false,"subreddit_id:""t5_2rk5q""",ups:2,approved_by:null,score:1,selftext_html:null,created:1310575520,hidden:false,over_18:false}

In [6]:
df_sample = pd.read_csv("subreddits24/3Dprinting_edges_2014_2025.csv", nrows = 5)
display(df_sample)

       SOURCE    TARGET   TIMESTAMP  SENTIMENT
0  3Dprinting     posts  1388688288          1
1  3Dprinting      IAmA  1388790076          1
2  3Dprinting  software  1388806617          1
3  3Dprinting         x  1388806617          1
4  3Dprinting    cradle  1388868067          1

In [7]:

df = pd.read_parquet('reddit_signed_edges_2014_2025.parquet')
df.head()

   SOURCE             TARGET   TIMESTAMP  SENTIMENT
0  baking  mildlyinteresting  1388704033          1
1  baking  mildlyinteresting  1388706092          1
2  baking         vegetarian  1388868199          1
3  baking               soda  1389110443          1
4  baking               beer  1389128303          1